spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/resident_helper?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: prod
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/resident_helper?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver